### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by Urammar** [Raicuparta/nomai-vr#551]
* Game Version: BuildID 12228193 (patch 14) Echos of the eye DLC
* OWML Version: 0.13.2
* NomaiVR Version: 2.9.2
* VR hardware: Rift CV1 + Touch controllers

 
Crash to desktop in the first few minutes of playing. OWML set to console logging, this is the log I have.

Never doing anything unusual, just flying around or even just moments after waking up, instant crash ::(

`Started OWML v2.11.1
Game found in G:/Steamlib/steamapps/common/Outer Wilds
Game version: 1.1.14.768
Game files copied.
Found mods:
* Raicuparta.NomaiVR v2.9.2
Copying OWML files...
Copying replacement OW files...
Patching OW assembly...
- Assembly is already patched.
Updating incremental GC...
Executing patcher for Raicuparta.NomaiVR v2.9.2
Identified as a Steam install. Launching...
Console connected to socket!
[OWML.Owo] : Mod loader has been initialized.
[OWML.Owo] : Game version: 1.1.14.768
[OWML.EnumUtils] : Initializing enum creator
[NomaiVR.Logs] : Error - method DialogueOptionUI.Awake not found.
[NomaiVR.HarmonyHelper] : Error in Patch: original MethodInfo is null.
Error while listening: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at OWML.Launcher.SocketListener.ListenToSocket() in D:\a\owml\owml\src\OWML.Launcher\SocketListener.cs:line 77
   at OWML.Launcher.SocketListener.SetupSocketListener() in D:\a\owml\owml\src\OWML.Launcher\SocketListener.cs:line 42`

**Comment by Urammar** [comment]
This was caused by migrating Outer Wilds across drives with steams built in interface. This was resolved with a re-install to the desired directory.
